// Konsolidiert enriched-Dateien einer Familie zu einer einzigen *_enriched.yaml,
// sortiert nach Code. Liest alle Eingabe-Dateien (raw YAML) und schreibt sie
// in der Reihenfolge ihrer Codes wieder raus, mit ein-Leerzeile-Trenner.
//
// Sortierung: alphabetisch nach Code (z. B. P0001, P0002, ..., P000A, P000B, ...)
// Das ist hex-aufsteigend, weil 0-9 < A-F in ASCII.

import { readFileSync, writeFileSync } from "node:fs";

const [, , outputPath, ...inputs] = process.argv;
if (!outputPath || inputs.length === 0) {
  console.error("Usage: node consolidate.mjs <output> <input1> [input2 ...]");
  process.exit(1);
}

// Schutz vor Argument-Vertausch (siehe wave-19 C0-Lesson):
// Output MUSS dem Familien-Naming `<F>xxx_enriched.yaml` folgen.
// Verhindert, dass eine Tranchen-Datei wie `_temp/u0_t1.yaml` versehentlich
// als Output angegeben und damit überschrieben wird.
if (!/_enriched\.yaml$/.test(outputPath)) {
  console.error(`ABBRUCH: Output "${outputPath}" endet nicht auf "_enriched.yaml".`);
  console.error("Argument-Reihenfolge ist: <output> <input1> [input2 ...] — Output zuerst.");
  process.exit(1);
}

// Parse jede Eingabe-Datei in Code-Block-Map.
// Jeder Block beginnt mit "- code: XXXXX" und endet vor dem nächsten "- code:".
const blocks = [];
for (const input of inputs) {
  const lines = readFileSync(input, "utf8").split(/\r?\n/);
  let current = null;
  let currentCode = null;
  for (const line of lines) {
    const m = line.match(/^- code:\s*([A-Z][0-9A-F]{4})/);
    if (m) {
      if (current) blocks.push({ code: currentCode, text: current.join("\n") });
      currentCode = m[1];
      current = [line];
    } else if (current) {
      // Leerzeilen am Ende jedes Blocks ignorieren — Konkatenation fügt eine ein
      current.push(line);
    }
    // Header-Kommentare vor erstem Block werden ignoriert
  }
  if (current) blocks.push({ code: currentCode, text: current.join("\n") });
}

// Trim trailing empty lines aus jedem Block-Text
for (const b of blocks) {
  b.text = b.text.replace(/\n+$/, "");
}

// Duplicate-Check
const seen = new Set();
for (const b of blocks) {
  if (seen.has(b.code)) {
    console.error(`DUPLICATE: ${b.code}`);
    process.exit(2);
  }
  seen.add(b.code);
}

// Sortieren nach Code
blocks.sort((a, b) => a.code.localeCompare(b.code));

const header = `# Consolidated enriched DTC entries for ${blocks[0].code.slice(0, 1)}${blocks[0].code.slice(1, 2)}xxx family\n` +
  `# ${blocks.length} codes, sorted ascending by code identifier.\n` +
  `# Re-generated by tools — do not edit headers manually.\n\n`;

writeFileSync(outputPath, header + blocks.map(b => b.text).join("\n\n") + "\n", "utf8");
console.log(`OK: ${blocks.length} codes -> ${outputPath}`);
